apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
type: Opaque
data:
  POSTGRES_USER: dXNlcm5hbWU=        # Base64 encoded 'username'
  POSTGRES_PASSWORD: cGFzc3dvcmQ=    # Base64 encoded 'password'
  POSTGRES_DB: bXlkYg==              # Base64 encoded 'mydb'

